all:
	$(MAKE) -C loader
	$(MAKE) -C loader_game
	$(MAKE) -C ui
	$(MAKE) -C net

clean:
	$(MAKE) -C loader clean
	$(MAKE) -C loader_game clean
	$(MAKE) -C ui clean
	$(MAKE) -C net clean

clean-all: clean
	$(MAKE) -C loader clean-all
	$(MAKE) -C loader_game clean-all
	$(MAKE) -C ui clean-all
	$(MAKE) -C net clean-all
